
# Copyright © 2023, V0L4T1LE
# All rights reserved.


Memory_Aid_Aliases = {
    "prim surv": "Primary Patient Assessment.txt",
    "Prim surv": "Primary Patient Assessment.txt",
    "Prim Surv": "Primary Patient Assessment.txt",
    "primary survey": "Primary Patient Assessment.txt",
    "Primary survey": "Primary Patient Assessment.txt",
    "Primary Survey": "Primary Patient Assessment.txt",
    "abcde": "Primary Patient Assessment.txt",
    "Abcde": "Primary Patient Assessment.txt",
    "ABCDE": "Primary Patient Assessment.txt",
    "cabcde": "Primary Patient Assessment.txt",
    "Cabcde": "Primary Patient Assessment.txt",
    "CABCDE": "Primary Patient Assessment.txt",
    "<c>abcde": "Primary Patient Assessment.txt",
    "<C>abcde": "Primary Patient Assessment.txt",
    "<c>ABCDE": "Primary Patient Assessment.txt",
    "<C>ABCDE": "Primary Patient Assessment.txt",
    "drabcde": "Primary Patient Assessment.txt",
    "Drabcde": "Primary Patient Assessment.txt",
    "DRABCDE": "Primary Patient Assessment.txt",
    "drcacbcde": "Primary Patient Assessment.txt",
    "Drcacbcde": "Primary Patient Assessment.txt",
    "DRcAcBCDE": "Primary Patient Assessment.txt",
    "DRCACBCDE": "Primary Patient Assessment.txt",
    "primary scene survey": "Primary Patient Assessment.txt",
    "Primary scene survey": "Primary Patient Assessment.txt",
    "Primary Scene Survey": "Primary Patient Assessment.txt",
    "primary patient survey": "Primary Patient Assessment.txt",
    "Primary patient survey": "Primary Patient Assessment.txt",
    "Primary Patient Survey": "Primary Patient Assessment.txt",
    "primary patient assessment": "Primary Patient Assessment.txt",
    "Primary patient assessment": "Primary Patient Assessment.txt",
    "Primary Patient Assessment": "Primary Patient Assessment.txt",
    "sample": "Secondary Patient Assessment.txt",
    "Sample": "Secondary Patient Assessment.txt",
    "SAMPLE": "Secondary Patient Assessment.txt",
    "sample survey": "Secondary Patient Assessment.txt",
    "Sample survey": "Secondary Patient Assessment.txt",
    "SAMPLE survey": "Secondary Patient Assessment.txt",
    "SAMPLE Survey": "Secondary Patient Assessment.txt",
    "sample assessment": "Secondary Patient Assessment.txt",
    "Sample assessment": "Secondary Patient Assessment.txt",
    "SAMPLE assessment": "Secondary Patient Assessment.txt",
    "SAMPLE Assessment": "Secondary Patient Assessment.txt",
    "sec surv": "Secondary Patient Assessment.txt",
    "Sec surv": "Secondary Patient Assessment.txt",
    "Sec Surv": "Secondary Patient Assessment.txt",
    "second survey": "Secondary Patient Assessment.txt",
    "Second survey": "Secondary Patient Assessment.txt",
    "Second Survey": "Secondary Patient Assessment.txt",
    "secondary survey": "Secondary Patient Assessment.txt",
    "Secondary survey": "Secondary Patient Assessment.txt",
    "Secondary Survey": "Secondary Patient Assessment.txt",
    "secondary patient assessment": "Secondary Patient Assessment.txt",
    "Secondary patient assessment": "Secondary Patient Assessment.txt",
    "Secondary Patient Assessment": "Secondary Patient Assessment.txt",
    "pain": "Pre-Hospital Pain Assessment.txt",
    "Pain": "Pre-Hospital Pain Assessment.txt",
    "pain test": "Pre-Hospital Pain Assessment.txt",
    "Pain test": "Pre-Hospital Pain Assessment.txt",
    "Pain Test": "Pre-Hospital Pain Assessment.txt",
    "pain review": "Pre-Hospital Pain Assessment.txt",
    "Pain review": "Pre-Hospital Pain Assessment.txt",
    "Pain Review": "Pre-Hospital Pain Assessment.txt",
    "pain assessment": "Pre-Hospital Pain Assessment.txt",
    "Pain assessment": "Pre-Hospital Pain Assessment.txt",
    "Pain Assessment": "Pre-Hospital Pain Assessment.txt",
    "prehospital pain assessment": "Pre-Hospital Pain Assessment.txt",
    "Prehospital pain assessment": "Pre-Hospital Pain Assessment.txt",
    "Prehospital Pain Assessment": "Pre-Hospital Pain Assessment.txt",
    "pre-hospital pain assessment": "Pre-Hospital Pain Assessment.txt",
    "Pre-hospital pain assessment": "Pre-Hospital Pain Assessment.txt",
    "Pre-hospital Pain Assessment": "Pre-Hospital Pain Assessment.txt",
    "opqrst": "Pre-Hospital Pain Assessment.txt",
    "Opqrst": "Pre-Hospital Pain Assessment.txt",
    "OPQRST": "Pre-Hospital Pain Assessment.txt",
    "opqrst assessment": "Pre-Hospital Pain Assessment.txt",
    "Opqrst assessment": "Pre-Hospital Pain Assessment.txt",
    "Opqrst Assessment": "Pre-Hospital Pain Assessment.txt",
    "OPQRST assessment": "Pre-Hospital Pain Assessment.txt",
    "OPQRST Assessment": "Pre-Hospital Pain Assessment.txt",
    "secondary pain assessment": "In-Hospital Pain Assessment.txt",
    "Secondary pain assessment": "In-Hospital Pain Assessment.txt",
    "Secondary Pain Assessment": "In-Hospital Pain Assessment.txt",
    "socrates": "In-Hospital Pain Assessment.txt",
    "Socrates": "In-Hospital Pain Assessment.txt",
    "SOCRATES": "In-Hospital Pain Assessment.txt",
    "socrates assessment": "In-Hospital Pain Assessment.txt",
    "Socrates assessment": "In-Hospital Pain Assessment.txt",
    "Socrates Assessment": "In-Hospital Pain Assessment.txt",
    "SOCRATES assessment": "In-Hospital Pain Assessment.txt",
    "SOCRATES Assessment": "In-Hospital Pain Assessment.txt",
    "hosp pain test": "In-Hospital Pain Assessment.txt",
    "Hosp pain test": "In-Hospital Pain Assessment.txt",
    "Hosp Pain Test": "In-Hospital Pain Assessment.txt",
    "hospital pain assessment": "In-Hospital Pain Assessment.txt",
    "Hospital pain assessment": "In-Hospital Pain Assessment.txt",
    "Hospital Pain Assessment": "In-Hospital Pain Assessment.txt",
    "in-hospital pain assessment": "In-Hospital Pain Assessment.txt",
    "In-hospital pain assessment": "In-Hospital Pain Assessment.txt",
    "In-hospital Pain Assessment": "In-Hospital Pain Assessment.txt",
    "In-Hospital Pain Assessment": "In-Hospital Pain Assessment.txt",
    "avpu": "AVPU Assessment.txt",
    "Avpu": "AVPU Assessment.txt",
    "AVPU": "AVPU Assessment.txt",
    "avpu assessment": "AVPU Assessment.txt",
    "Avpu assessment": "AVPU Assessment.txt",
    "AVPU assessment": "AVPU Assessment.txt",
    "AVPU Assessment": "AVPU Assessment.txt",
    "response": "AVPU Assessment.txt",
    "Response": "AVPU Assessment.txt",
    "responsiveness": "AVPU Assessment.txt",
    "Responsiveness": "AVPU Assessment.txt",
    "pt response": "AVPU Assessment.txt",
    "PT response": "AVPU Assessment.txt",
    "PT Response": "AVPU Assessment.txt",
    "patient response": "AVPU Assessment.txt",
    "Patient response": "AVPU Assessment.txt",
    "Patient Response": "AVPU Assessment.txt",
    "patient alertness": "AVPU Assessment.txt",
    "Patient alertness": "AVPU Assessment.txt",
    "Patient Alertness": "AVPU Assessment.txt",
    "patient responsiveness": "AVPU Assessment.txt",
    "Patient responsiveness": "AVPU Assessment.txt",
    "Patient Responsiveness": "AVPU Assessment.txt",
    "gcs": "Glasgow Coma Scale.txt",
    "Gcs": "Glasgow Coma Scale.txt",
    "GCS": "Glasgow Coma Scale.txt",
    "gcs scale": "Glasgow Coma Scale.txt",
    "Gcs scale": "Glasgow Coma Scale.txt",
    "Gcs Scale": "Glasgow Coma Scale.txt",
    "GCS scale": "Glasgow Coma Scale.txt",
    "GCS Scale": "Glasgow Coma Scale.txt",
    "glasgow coma scale": "Glasgow Coma Scale.txt",
    "Glasgow coma scale": "Glasgow Coma Scale.txt",
    "Glasgow Coma Scale": "Glasgow Coma Scale.txt",
    "ddd": "Beck's Triad.txt",
    "Ddd": "Beck's Triad.txt",
    "DDD": "Beck's Triad.txt",
    "3d's": "Beck's Triad.txt",
    "3D's": "Beck's Triad.txt",
    "3ds": "Beck's Triad.txt",
    "3Ds": "Beck's Triad.txt",
    "3 ds": "Beck's Triad.txt",
    "3 Ds": "Beck's Triad.txt",
    "3 d's": "Beck's Triad.txt",
    "3 D's": "Beck's Triad.txt",
    "three ds": "Beck's Triad.txt",
    "Three ds": "Beck's Triad.txt",
    "Three Ds": "Beck's Triad.txt",
    "three d's": "Beck's Triad.txt",
    "Three d's": "Beck's Triad.txt",
    "Three D's": "Beck's Triad.txt",
    "becks triad": "Beck's Triad.txt",
    "Becks triad": "Beck's Triad.txt",
    "Becks Triad": "Beck's Triad.txt",
    "beck's triad": "Beck's Triad.txt",
    "Beck's triad": "Beck's Triad.txt",
    "Beck's Triad": "Beck's Triad.txt",
    "cardiac tamponade indics": "Beck's Triad.txt",
    "Cardiac tamponade indics": "Beck's Triad.txt",
    "Cardiac Tamponade Indics": "Beck's Triad.txt",
    "cardiac tamponade indications": "Beck's Triad.txt",
    "Cardiac tamponade indications": "Beck's Triad.txt",
    "Cardiac Tamponade Indications": "Beck's Triad.txt",
    "pericard indics": "Beck's Triad.txt",
    "Pericard indics": "Beck's Triad.txt",
    "Pericard Indics": "Beck's Triad.txt",
    "pericard indications": "Beck's Triad.txt",
    "Pericard indications": "Beck's Triad.txt",
    "Pericard Indications": "Beck's Triad.txt",
    "must": "Malnutrition Universal Screening Tool.txt",
    "Must": "Malnutrition Universal Screening Tool.txt",
    "MUST": "Malnutrition Universal Screening Tool.txt",
    "must tool": "Malnutrition Universal Screening Tool.txt",
    "Must tool": "Malnutrition Universal Screening Tool.txt",
    "Must Tool": "Malnutrition Universal Screening Tool.txt",
    "MUST tool": "Malnutrition Universal Screening Tool.txt",
    "MUST Tool": "Malnutrition Universal Screening Tool.txt",
    "malnutrition": "Malnutrition Universal Screening Tool.txt",
    "Malnutrition": "Malnutrition Universal Screening Tool.txt",
    "malnutrition tool": "Malnutrition Universal Screening Tool.txt",
    "Malnutrition tool": "Malnutrition Universal Screening Tool.txt",
    "Malnutrition Tool": "Malnutrition Universal Screening Tool.txt",
    "patient malnutrition": "Malnutrition Universal Screening Tool.txt",
    "Patient malnutrition": "Malnutrition Universal Screening Tool.txt",
    "Patient Malnutrition": "Malnutrition Universal Screening Tool.txt",
    "malnutrition screening tool": "Malnutrition Universal Screening Tool.txt",
    "Malnutrition screening tool": "Malnutrition Universal Screening Tool.txt",
    "Malnutrition Screening Tool": "Malnutrition Universal Screening Tool.txt",
    "malnutrition assessment tool": "Malnutrition Universal Screening Tool.txt",
    "Malnutrition assessment tool": "Malnutrition Universal Screening Tool.txt",
    "Malnutrition Assessment Tool": "Malnutrition Universal Screening Tool.txt",
    "universal malnutrition assessment tool": "Malnutrition Universal Screening Tool.txt",
    "Universal malnutrition assessment tool": "Malnutrition Universal Screening Tool.txt",
    "Universal Malnutrition Assessment Tool": "Malnutrition Universal Screening Tool.txt",
    "universal malnutrition screening tool": "Malnutrition Universal Screening Tool.txt",
    "Universal malnutrition screening tool": "Malnutrition Universal Screening Tool.txt",
    "Universal Malnutrition Screening Tool": "Malnutrition Universal Screening Tool.txt",
    "malnutrition universal screening tool": "Malnutrition Universal Screening Tool.txt",
    "Malnutrition universal screening tool": "Malnutrition Universal Screening Tool.txt",
    "Malnutrition Universal Screening Tool": "Malnutrition Universal Screening Tool.txt",
    "cpot": "Critical Care Pain Observation Tool.txt",
    "Cpot": "Critical Care Pain Observation Tool.txt",
    "CPOT": "Critical Care Pain Observation Tool.txt",
    "ccpot": "Critical Care Pain Observation Tool.txt",
    "Ccpot": "Critical Care Pain Observation Tool.txt",
    "CCPOT": "Critical Care Pain Observation Tool.txt",
    "cc pot": "Critical Care Pain Observation Tool.txt",
    "Cc pot": "Critical Care Pain Observation Tool.txt",
    "Cc Pot": "Critical Care Pain Observation Tool.txt",
    "CC POT": "Critical Care Pain Observation Tool.txt",
    "cc-pot": "Critical Care Pain Observation Tool.txt",
    "Cc-pot": "Critical Care Pain Observation Tool.txt",
    "CC-POT": "Critical Care Pain Observation Tool.txt",
    "cc pain obs tool": "Critical Care Pain Observation Tool.txt",
    "CC pain obs tool": "Critical Care Pain Observation Tool.txt",
    "CC Pain obs tool": "Critical Care Pain Observation Tool.txt",
    "CC Pain Obs Tool": "Critical Care Pain Observation Tool.txt",
    "cc pain observations tool": "Critical Care Pain Observation Tool.txt",
    "CC pain observations tool": "Critical Care Pain Observation Tool.txt",
    "CC Pain observations tool": "Critical Care Pain Observation Tool.txt",
    "CC Pain Observations Tool": "Critical Care Pain Observation Tool.txt",
    "pain observation tool": "Critical Care Pain Observation Tool.txt",
    "Pain observation tool": "Critical Care Pain Observation Tool.txt",
    "Pain Observation Tool": "Critical Care Pain Observation Tool.txt",
    "critical pain observation tool": "Critical Care Pain Observation Tool.txt",
    "Critical pain observation tool": "Critical Care Pain Observation Tool.txt",
    "Critical Pain Observation Tool": "Critical Care Pain Observation Tool.txt",
    "critical care pain observation tool": "Critical Care Pain Observation Tool.txt",
    "Critical care pain observation tool": "Critical Care Pain Observation Tool.txt",
    "Critical Care Pain Observation Tool": "Critical Care Pain Observation Tool.txt",
    "critical-care pain observation tool": "Critical Care Pain Observation Tool.txt",
    "Critical-care pain observation tool": "Critical Care Pain Observation Tool.txt",
    "Critical-care Pain Observation Tool": "Critical Care Pain Observation Tool.txt",
    "Critical-Care Pain Observation Tool": "Critical Care Pain Observation Tool.txt",
    "bps": "Behavioural Pain Score.txt",
    "Bps": "Behavioural Pain Score.txt",
    "BPS": "Behavioural Pain Score.txt",
    "bps tool": "Behavioural Pain Score.txt",
    "Bps tool": "Behavioural Pain Score.txt",
    "Bps Tool": "Behavioural Pain Score.txt",
    "BPS tool": "Behavioural Pain Score.txt",
    "BPS Tool": "Behavioural Pain Score.txt",
    "behavioural pain score": "Behavioural Pain Score.txt",
    "Behavioural pain score": "Behavioural Pain Score.txt",
    "Behavioural Pain Score": "Behavioural Pain Score.txt",
    "behavioural pain score tool": "Behavioural Pain Score.txt",
    "Behavioural pain score tool": "Behavioural Pain Score.txt",
    "Behavioural Pain Score Tool": "Behavioural Pain Score.txt",
    "gcs p": "Glasgow Coma Scale (2018).txt",
    "Gcs p": "Glasgow Coma Scale (2018).txt",
    "Gcs P": "Glasgow Coma Scale (2018).txt",
    "GCS P": "Glasgow Coma Scale (2018).txt",
    "gcs-p": "Glasgow Coma Scale (2018).txt",
    "Gcs-p": "Glasgow Coma Scale (2018).txt",
    "Gcs-P": "Glasgow Coma Scale (2018).txt",
    "GCS-P": "Glasgow Coma Scale (2018).txt",
    "2018 gcs": "Glasgow Coma Scale (2018).txt",
    "2018 Gcs": "Glasgow Coma Scale (2018).txt",
    "2018 GCS": "Glasgow Coma Scale (2018).txt",
    "gcs 2018": "Glasgow Coma Scale (2018).txt",
    "Gcs 2018": "Glasgow Coma Scale (2018).txt",
    "GCS 2018": "Glasgow Coma Scale (2018).txt",
    "gcs (2018)": "Glasgow Coma Scale (2018).txt",
    "Gcs (2018)": "Glasgow Coma Scale (2018).txt",
    "GCS (2018)": "Glasgow Coma Scale (2018).txt",
    "2018 gcs scale": "Glasgow Coma Scale (2018).txt",
    "2018 Gcs scale": "Glasgow Coma Scale (2018).txt",
    "2018 Gcs Scale": "Glasgow Coma Scale (2018).txt",
    "2018 GCS scale": "Glasgow Coma Scale (2018).txt",
    "2018 GCS Scale": "Glasgow Coma Scale (2018).txt",
    "gcs scale 2018": "Glasgow Coma Scale (2018).txt",
    "Gcs scale 2018": "Glasgow Coma Scale (2018).txt",
    "Gcs Scale 2018": "Glasgow Coma Scale (2018).txt",
    "GCS scale 2018": "Glasgow Coma Scale (2018).txt",
    "GCS Scale 2018": "Glasgow Coma Scale (2018).txt",
    "pupil gcs": "Glasgow Coma Scale (2018).txt",
    "pupil GCS": "Glasgow Coma Scale (2018).txt",
    "Pupil gcs": "Glasgow Coma Scale (2018).txt",
    "Pupil Gcs": "Glasgow Coma Scale (2018).txt",
    "Pupil GCS": "Glasgow Coma Scale (2018).txt",
    "pupillary gcs": "Glasgow Coma Scale (2018).txt",
    "pupillary GCS": "Glasgow Coma Scale (2018).txt",
    "Pupillary gcs": "Glasgow Coma Scale (2018).txt",
    "Pupillary Gcs": "Glasgow Coma Scale (2018).txt",
    "Pupillary GCS": "Glasgow Coma Scale (2018).txt",
    "perrla gcs": "Glasgow Coma Scale (2018).txt",
    "Perrla gcs": "Glasgow Coma Scale (2018).txt",
    "Perrla Gcs": "Glasgow Coma Scale (2018).txt",
    "PERRLA GCS": "Glasgow Coma Scale (2018).txt",
    "gcs pearl": "Glasgow Coma Scale (2018).txt",
    "Gcs pearl": "Glasgow Coma Scale (2018).txt",
    "Gcs Pearl": "Glasgow Coma Scale (2018).txt",
    "GCS pearl": "Glasgow Coma Scale (2018).txt",
    "GCS Pearl": "Glasgow Coma Scale (2018).txt",
    "GCS PEARL": "Glasgow Coma Scale (2018).txt",
    "new gcs": "Glasgow Coma Scale (2018).txt",
    "new GCS": "Glasgow Coma Scale (2018).txt",
    "New gcs": "Glasgow Coma Scale (2018).txt",
    "New Gcs": "Glasgow Coma Scale (2018).txt",
    "New GCS": "Glasgow Coma Scale (2018).txt",
    "new gcs scale": "Glasgow Coma Scale (2018).txt",
    "New gcs scale": "Glasgow Coma Scale (2018).txt",
    "New GCS Scale": "Glasgow Coma Scale (2018).txt",
    "antidote": "Common Antidotes.txt",
    "Antidote": "Common Antidotes.txt",
    "antidotes": "Common Antidotes.txt",
    "Antidotes": "Common Antidotes.txt",
    "reversal agent": "Common Antidotes.txt",
    "Reversal agent": "Common Antidotes.txt",
    "Reversal Agent": "Common Antidotes.txt",
    "reversal agents": "Common Antidotes.txt",
    "Reversal agents": "Common Antidotes.txt",
    "Reversal Agents": "Common Antidotes.txt",
    "anti toxins": "Common Antidotes.txt",
    "Anti toxins": "Common Antidotes.txt",
    "Anti Toxins": "Common Antidotes.txt",
    "anti-toxins": "Common Antidotes.txt",
    "Anti-toxins": "Common Antidotes.txt",
    "Anti-Toxins": "Common Antidotes.txt",
    "common antidotes": "Common Antidotes.txt",
    "Common antidotes": "Common Antidotes.txt",
    "Common Antidotes": "Common Antidotes.txt",
    "sludgem": "Nerve Agent Exposure Mnemonic.txt",
    "Sludgem": "Nerve Agent Exposure Mnemonic.txt",
    "SLUDGEM": "Nerve Agent Exposure Mnemonic.txt",
    "sludgem mnemonic": "Nerve Agent Exposure Mnemonic.txt",
    "Sludgem mnemonic": "Nerve Agent Exposure Mnemonic.txt",
    "Sludgem Mnemonic": "Nerve Agent Exposure Mnemonic.txt",
    "SLUDGEM mnemonic": "Nerve Agent Exposure Mnemonic.txt",
    "SLUDGEM Mnemonic": "Nerve Agent Exposure Mnemonic.txt",
    "nerve agent exposure": "Nerve Agent Exposure Mnemonic.txt",
    "Nerve agent exposure": "Nerve Agent Exposure Mnemonic.txt",
    "Nerve Agent Exposure": "Nerve Agent Exposure Mnemonic.txt",
    "nerve agent indicators": "Nerve Agent Exposure Mnemonic.txt",
    "Nerve agent indicators": "Nerve Agent Exposure Mnemonic.txt",
    "Nerve Agent Indicators": "Nerve Agent Exposure Mnemonic.txt",
    "nerve agent indications": "Nerve Agent Exposure Mnemonic.txt",
    "Nerve agent indications": "Nerve Agent Exposure Mnemonic.txt",
    "Nerve Agent Indications": "Nerve Agent Exposure Mnemonic.txt",
    "nerve agent exposure mnemonic": "Nerve Agent Exposure Mnemonic.txt",
    "Nerve agent exposure mnemonic": "Nerve Agent Exposure Mnemonic.txt",
    "Nerve Agent Exposure Mnemonic": "Nerve Agent Exposure Mnemonic.txt",
    "nerve agent exposure indicators": "Nerve Agent Exposure Mnemonic.txt",
    "Nerve agent exposure indicators": "Nerve Agent Exposure Mnemonic.txt",
    "Nerve Agent Exposure Indicators": "Nerve Agent Exposure Mnemonic.txt",
    "nerve agent exposure indications": "Nerve Agent Exposure Mnemonic.txt",
    "Nerve agent exposure indications": "Nerve Agent Exposure Mnemonic.txt",
    "Nerve Agent Exposure Indications": "Nerve Agent Exposure Mnemonic.txt",
    "5ps": "Neurovascular Assessment.txt",
    "5Ps": "Neurovascular Assessment.txt",
    "5p's": "Neurovascular Assessment.txt",
    "5P's": "Neurovascular Assessment.txt",
    "five ps": "Neurovascular Assessment.txt",
    "Five ps": "Neurovascular Assessment.txt",
    "Five Ps": "Neurovascular Assessment.txt",
    "five p's": "Neurovascular Assessment.txt",
    "five P's": "Neurovascular Assessment.txt",
    "Five p's": "Neurovascular Assessment.txt",
    "Five P's": "Neurovascular Assessment.txt",
    "neurovasc": "Neurovascular Assessment.txt",
    "Neurovasc": "Neurovascular Assessment.txt",
    "neurovasc assessment": "Neurovascular Assessment.txt",
    "Neurovasc assessment": "Neurovascular Assessment.txt",
    "Neurovasc Assessment": "Neurovascular Assessment.txt",
    "neurovascular assessment": "Neurovascular Assessment.txt",
    "Neurovascular assessment": "Neurovascular Assessment.txt",
    "Neurovascular Assessment": "Neurovascular Assessment.txt",
    "fractures": "Types of Fracture.txt",
    "Fractures": "Types of Fracture.txt",
    "fx's": "Types of Fracture.txt",
    "Fx's": "Types of Fracture.txt",
    "fx types": "Types of Fracture.txt",
    "Fx types": "Types of Fracture.txt",
    "Fx Types": "Types of Fracture.txt",
    "fracture types": "Types of Fracture.txt",
    "Fracture types": "Types of Fracture.txt",
    "Fracture Types": "Types of Fracture.txt",
    "types of fx": "Types of Fracture.txt",
    "Types of fx": "Types of Fracture.txt",
    "Types of Fx": "Types of Fracture.txt",
    "Types Of Fx": "Types of Fracture.txt",
    "types of fracture": "Types of Fracture.txt",
    "Types of fracture": "Types of Fracture.txt",
    "Types of Fracture": "Types of Fracture.txt",
    "Types Of Fracture": "Types of Fracture.txt",
    "prealert": "ASHICE Pre-Alert.txt",
    "Prealert": "ASHICE Pre-Alert.txt",
    "pre alert": "ASHICE Pre-Alert.txt",
    "Pre alert": "ASHICE Pre-Alert.txt",
    "Pre Alert": "ASHICE Pre-Alert.txt",
    "pre-alert": "ASHICE Pre-Alert.txt",
    "Pre-alert": "ASHICE Pre-Alert.txt",
    "Pre-Alert": "ASHICE Pre-Alert.txt",
    "hospital prealert": "ASHICE Pre-Alert.txt",
    "Hospital prealert": "ASHICE Pre-Alert.txt",
    "Hospital Prealert": "ASHICE Pre-Alert.txt",
    "hospital pre-alert": "ASHICE Pre-Alert.txt",
    "Hospital pre-alert": "ASHICE Pre-Alert.txt",
    "Hospital Pre-alert": "ASHICE Pre-Alert.txt",
    "Hospital Pre-Alert": "ASHICE Pre-Alert.txt",
    "ashice": "ASHICE Pre-Alert.txt",
    "Ashice": "ASHICE Pre-Alert.txt",
    "ASHICE": "ASHICE Pre-Alert.txt",
    "ashice pre-alert": "ASHICE Pre-Alert.txt",
    "Ashice pre-alert": "ASHICE Pre-Alert.txt",
    "Ashice Pre-alert": "ASHICE Pre-Alert.txt",
    "Ashice Pre-Alert": "ASHICE Pre-Alert.txt",
    "ASHICE pre-alert": "ASHICE Pre-Alert.txt",
    "ASHICE Pre-alert": "ASHICE Pre-Alert.txt",
    "ASHICE Pre-Alert": "ASHICE Pre-Alert.txt",
}

Medication_Aliases = {
    "epipen": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "Epipen": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "EpiPen": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "epi-pen": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "Epi-pen": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "Epi-Pen": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "epi pen": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "Epi pen": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "Epi Pen": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "epi injector": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "Epi injector": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "Epi Injector": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "im epi": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "Im epi": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "IM epi": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "IM Epi": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "im epinephrine": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "Im epinephrine": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "IM epinephrine": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "IM Epinephrine": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "epinephrine ai": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "Epinephrine ai": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "Epinephrine AI": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "epi 1:1000": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "Epi 1:1000": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "epi 1:1,000": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "Epi 1:1,000": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "1:1000 epi": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "1:1000 Epi": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "1:1,000 epi": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "1:1,000 Epi": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "epi 1;1000": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "Epi 1;1000": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "epi 1;1,000": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "Epi 1;1,000": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "1;1000 epi": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "1;1000 Epi": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "1;1,000 epi": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "1;1,000 Epi": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "1mg/mL epi": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "1mg/mL Epi": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "1mg/ml epi": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "1mg/ml Epi": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "1mg/1mL epi": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "1mg/1mL Epi": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "1mg/1ml epi": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "1mg/1ml Epi": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "mg/ml epi": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "mg/ml Epi": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "Mg/ml epi": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "mg/mL epi": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "mg/mL Epi": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "epinephrine autoinjector": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "Epinephrine autoinjector": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "Epinephrine Autoinjector": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "epinephrine auto-injector": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "Epinephrine auto-injector": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "Epinephrine Auto-injector": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "Epinephrine Auto-Injector": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "adrenaline autoinjector": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "Adrenaline autoinjector": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "Adrenaline Autoinjector": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "adrenaline auto-injector": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "Adrenaline auto-injector": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "Adrenaline Auto-injector": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "Adrenaline Auto-Injector": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "adrenaline pen": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "Adrenaline pen": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "Adrenaline Pen": "CO1CA24  -  Epinephrine (1 ; 1,000).txt",
    "v03an01": "V03AN01  -  Medical Oxygen (10 - 100%).txt",
    "V03AN01": "V03AN01  -  Medical Oxygen (10 - 100%).txt",
    "oxy": "V03AN01  -  Medical Oxygen (10 - 100%).txt",
    "Oxy": "V03AN01  -  Medical Oxygen (10 - 100%).txt",
    "oxygen": "V03AN01  -  Medical Oxygen (10 - 100%).txt",
    "Oxygen": "V03AN01  -  Medical Oxygen (10 - 100%).txt",
    "o2": "V03AN01  -  Medical Oxygen (10 - 100%).txt",
    "O2": "V03AN01  -  Medical Oxygen (10 - 100%).txt",
    "conc o2": "V03AN01  -  Medical Oxygen (10 - 100%).txt",
    "Conc o2": "V03AN01  -  Medical Oxygen (10 - 100%).txt",
    "conc O2": "V03AN01  -  Medical Oxygen (10 - 100%).txt",
    "Conc O2": "V03AN01  -  Medical Oxygen (10 - 100%).txt",
    "concentrated oxygen": "V03AN01  -  Medical Oxygen (10 - 100%).txt",
    "Concentrated oxygen": "V03AN01  -  Medical Oxygen (10 - 100%).txt",
    "Concentrated Oxygen": "V03AN01  -  Medical Oxygen (10 - 100%).txt",
    "c01ca24": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "C01ca24": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "C01CA24": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "epi": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "Epi": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "adren": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "Adren": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "adrenaline": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "Adrenaline": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "epinephrine": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "Epinephrine": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "epi injection": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "Epi injection": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "Epi Injection": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "epi for injection": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "Epi for injection": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "Epi for Injection": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "Epi For Injection": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "1mg/10ml epi": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "1mg/10ml Epi": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "1mg/10mL epi": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "1mg/10mL Epi": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "0.1mg/ml epi": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "0.1mg/ml Epi": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "0.1mg/mL epi": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "0.1mg/mL Epi": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "1mg/10mL Epi": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "0.1mg/1ml epi": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "0.1mg/1ml Epi": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "0.1mg/1mL epi": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "0.1mg/1mL Epi": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "1:10000 epi": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "1:10000 Epi": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "1:10,000 epi": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "1:10,000 Epi": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "1;10000 epi": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "1;10000 Epi": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "1;10,000 epi": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "1;10,000 Epi": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "epi 1:10000": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "Epi 1:10000": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "epi 1:10,000": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "Epi 1:10,000": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "epi 1;10000": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "Epi 1;10000": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "epi 1;10,000": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "Epi 1;10,000": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "inj epi": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "Inj epi": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "INJ epi": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "Inj Epi": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "INJ Epi": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "epi syr": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "Epi syr": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "Epi Syr": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "epi syr.": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "Epi syr.": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "Epi Syr.": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "epi syringe": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "Epi syringe": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
    "Epi Syringe": "C01CA24  -  Epinephrine (1 ; 10,000).txt",
}

Procedure_Aliases = {
    "3 lead": "3-Lead Electrocardiogram Acquisition",
    "3 Lead": "3-Lead Electrocardiogram Acquisition",
    "3-lead": "3-Lead Electrocardiogram Acquisition",
    "3-Lead": "3-Lead Electrocardiogram Acquisition",
    "3 lead ecg": "3-Lead Electrocardiogram Acquisition",
    "3 Lead ECG": "3-Lead Electrocardiogram Acquisition",
    "3-lead ecg": "3-Lead Electrocardiogram Acquisition",
    "3-Lead ECG": "3-Lead Electrocardiogram Acquisition",
    "3 lead electrocardiogram": "3-Lead Electrocardiogram Acquisition",
    "3 Lead Electrocardiogram": "3-Lead Electrocardiogram Acquisition",
    "3-lead electrcardiogram": "3-Lead Electrocardiogram Acquisition",
    "3-Lead Electrocardiogram": "3-Lead Electrocardiogram Acquisition",
    "ecg": "12-Lead Electrocardiogram Acquisition",
    "ECG": "12-Lead Electrocardiogram Acquisition",
    "12 lead": "12-Lead Electrocardiogram Acquisition",
    "12 Lead": "12-Lead Electrocardiogram Acquisition",
    "12-lead": "12-Lead Electrocardiogram Acquisition",
    "12-Lead": "12-Lead Electrocardiogram Acquisition",
    "12 lead ECG": "12-Lead Electrocardiogram Acquisition",
    "12 Lead ECG": "12-Lead Electrocardiogram Acquisition",
    "12-lead ECG": "12-Lead Electrocardiogram Acquisition",
    "12-Lead ECG": "12-Lead Electrocardiogram Acquisition",
    "12 lead electrocardiogram": "12-Lead Electrocardiogram Acquisition",
    "12 Lead Electrocardiogram": "12-Lead Electrocardiogram Acquisition",
    "12-lead electrocardiogram": "12-Lead Electrocardiogram Acquisition",
    "12-Lead Electrocardiogram": "12-Lead Electrocardiogram Acquisition",
    "12 lead electrocardiogram acquisition": "12-Lead Electrocardiogram Acquisition",
    "12 Lead Electrocardiogram Acquisition": "12-Lead Electrocardiogram Acquisition",
    "12-lead electrocardiogram acquisition": "12-Lead Electrocardiogram Acquisition",
    "12-Lead Electrocardiogram Acquisition": "12-Lead Electrocardiogram Acquisition",
    "ABD evisc": "Abdominal Evisceration Management",
    "ABD Evisc": "Abdominal Evisceration Management",
    "abdo evis": "Abdominal Evisceration Management",
    "Abdo evis": "Abdominal Evisceration Management",
    "Abdo Evis": "Abdominal Evisceration Management",
    "abdo evisc": "Abdominal Evisceration Management",
    "Abdo evisc": "Abdominal Evisceration Management",
    "Abdo Evisc": "Abdominal Evisceration Management",
    "ABD evisceration": "Abdominal Evisceration Management",
    "ABD Evisceration": "Abdominal Evisceration Management",
    "Abdo evisceration": "Abdominal Evisceration Management",
    "Abdo Evisceration": "Abdominal Evisceration Management",
    "Abdominal evisceration": "Abdominal Evisceration Management",
    "Abdominal Evisceration": "Abdominal Evisceration Management",
    "Abdominal evisceration management": "Abdominal Evisceration Management",
    "Abdominal Evisceration Management": "Abdominal Evisceration Management",
    "part management": "Amputated Part Management",
    "Part management": "Amputated Part Management",
    "Part Management": "Amputated Part Management",
    "Amputation management": "Amputated Part Management",
    "Amputation Management": "Amputated Part Management",
    "Amputated part management": "Amputated Part Management",
    "Amputated Part Management": "Amputated Part Management",
    "abg": "Arterial Blood Gas Measurement",
    "Abg": "Arterial Blood Gas Measurement",
    "ABG": "Arterial Blood Gas Measurement",
    "abgs": "Arterial Blood Gas Measurement",
    "ABGs": "Arterial Blood Gas Measurement",
    "abg's": "Arterial Blood Gas Measurement",
    "ABG's": "Arterial Blood Gas Measurement",
    "abg assessment": "Arterial Blood Gas Measurement",
    "Abg assessment": "Arterial Blood Gas Measurement",
    "Abg Assessment": "Arterial Blood Gas Measurement",
    "ABG assessment": "Arterial Blood Gas Measurement",
    "ABG Assessment": "Arterial Blood Gas Measurement",
    "abg measurement": "Arterial Blood Gas Measurement",
    "Abg measurement": "Arterial Blood Gas Measurement",
    "Abg Measurement": "Arterial Blood Gas Measurement",
    "ABG measurement": "Arterial Blood Gas Measurement",
    "ABG Measurement": "Arterial Blood Gas Measurement",
    "blood gas": "Arterial Blood Gas Measurement",
    "Blood gas": "Arterial Blood Gas Measurement",
    "Blood Gas": "Arterial Blood Gas Measurement",
    "blood gases": "Arterial Blood Gas Measurement",
    "Blood gases": "Arterial Blood Gas Measurement",
    "Blood Gases": "Arterial Blood Gas Measurement",
    "arterial blood gas": "Arterial Blood Gas Measurement",
    "Arterial blood gas": "Arterial Blood Gas Measurement",
    "Arterial Blood Gas": "Arterial Blood Gas Measurement",
    "arterial blood gases": "Arterial Blood Gas Measurement",
    "Arterial blood gases": "Arterial Blood Gas Measurement",
    "Arterial Blood Gases": "Arterial Blood Gas Measurement",
    "arterial blood gas assessment": "Arterial Blood Gas Measurement",
    "Arterial blood gas assessment": "Arterial Blood Gas Measurement",
    "Arterial Blood Gas Assessment": "Arterial Blood Gas Measurement",
    "arterial blood gas measurement": "Arterial Blood Gas Measurement",
    "Arterial blood gas measurement": "Arterial Blood Gas Measurement",
    "Arterial Blood Gas Measurement": "Arterial Blood Gas Measurement",
    "nibp": "Digital Non-Invasive Blood Pressure Measurement",
    "NIBP": "Digital Non-Invasive Blood Pressure Measurement",
    "Digital nibp": "Digital Non-Invasive Blood Pressure Measurement",
    "Digital NIBP": "Digital Non-Invasive Blood Pressure Measurement",
    "nibp assessment": "Digital Non-Invasive Blood Pressure Measurement",
    "NIBP assessment": "Digital Non-Invasive Blood Pressure Measurement",
    "NIBP Assessment": "Digital Non-Invasive Blood Pressure Measurement",
    "nibp measurement": "Digital Non-Invasive Blood Pressure Measurement",
    "NIBP measurement": "Digital Non-Invasive Blood Pressure Measurement",
    "NIBP Measurement": "Digital Non-Invasive Blood Pressure Measurement",
    "digital nibp measurement": "Digital Non-Invasive Blood Pressure Measurement",
    "Digital nibp measurement": "Digital Non-Invasive Blood Pressure Measurement",
    "Digital NIBP Measurement": "Digital Non-Invasive Blood Pressure Measurement",
    "Digital Non-Invasive Blood Pressure Measurement": "Digital Non-Invasive Blood Pressure Measurement",
    "bvm": "Bag Valve Mask Ventilation",
    "Bvm": "Bag Valve Mask Ventilation",
    "BVM": "Bag Valve Mask Ventilation",
    "bvm vent": "Bag Valve Mask Ventilation",
    "Bvm vent": "Bag Valve Mask Ventilation",
    "BVM vent": "Bag Valve Mask Ventilation",
    "BVM Vent": "Bag Valve Mask Ventilation",
    "bvm ventilation": "Bag Valve Mask Ventilation",
    "Bvm ventilation": "Bag Valve Mask Ventilation",
    "BVM ventilation": "Bag Valve Mask Ventilation",
    "BVM Ventilation": "Bag Valve Mask Ventilation",
    "ambu mask": "Bag Valve Mask Ventilation",
    "Ambu mask": "Bag Valve Mask Ventilation",
    "Ambu Mask": "Bag Valve Mask Ventilation",
    "ambu bag": "Bag Valve Mask Ventilation",
    "Ambu bag": "Bag Valve Mask Ventilation",
    "Ambu Bag": "Bag Valve Mask Ventilation",
    "bag mask": "Bag Valve Mask Ventilation",
    "Bag mask": "Bag Valve Mask Ventilation",
    "Bag Mask": "Bag Valve Mask Ventilation",
    "resus bag": "Bag Valve Mask Ventilation",
    "Resus bag": "Bag Valve Mask Ventilation",
    "Resus Bag": "Bag Valve Mask Ventilation",
    "resus mask": "Bag Valve Mask Ventilation",
    "Resus mask": "Bag Valve Mask Ventilation",
    "Resus Mask": "Bag Valve Mask Ventilation",
    "bag valve mask": "Bag Valve Mask Ventilation",
    "Bag valve mask": "Bag Valve Mask Ventilation",
    "Bag Valve Mask": "Bag Valve Mask Ventilation",
    "Resus mask ventilation": "Bag Valve Mask Ventilation",
    "Resus Mask Ventilation": "Bag Valve Mask Ventilation",
    "spco": "Blood Carboxyhaemoglobin Measurement",
    "Spco": "Blood Carboxyhaemoglobin Measurement",
    "SpCO": "Blood Carboxyhaemoglobin Measurement",
    "cohb": "Blood Carboxyhaemoglobin Measurement",
    "Cohb": "Blood Carboxyhaemoglobin Measurement",
    "COHb": "Blood Carboxyhaemoglobin Measurement",
    "spco assessment": "Blood Carboxyhaemoglobin Measurement",
    "Spco assessment": "Blood Carboxyhaemoglobin Measurement",
    "SpCO assessment": "Blood Carboxyhaemoglobin Measurement",
    "SpCO Assessment": "Blood Carboxyhaemoglobin Measurement",
    "cohb assessment": "Blood Carboxyhaemoglobin Measurement",
    "Cohb assessment": "Blood Carboxyhaemoglobin Measurement",
    "COHb assessment": "Blood Carboxyhaemoglobin Measurement",
    "COHb Assessment": "Blood Carboxyhaemoglobin Measurement",
    "spco measurement": "Blood Carboxyhaemoglobin Measurement",
    "Spco measurement": "Blood Carboxyhaemoglobin Measurement",
    "SpCO measurement": "Blood Carboxyhaemoglobin Measurement",
    "SpCO Measurement": "Blood Carboxyhaemoglobin Measurement",
    "cohb measurement": "Blood Carboxyhaemoglobin Measurement",
    "Cohb measurement": "Blood Carboxyhaemoglobin Measurement",
    "COHb measurement": "Blood Carboxyhaemoglobin Measurement",
    "COHb Measurement": "Blood Carboxyhaemoglobin Measurement",
    "blood carboxy": "Blood Carboxyhaemoglobin Measurement",
    "Blood carboxy": "Blood Carboxyhaemoglobin Measurement",
    "Blood Carboxy": "Blood Carboxyhaemoglobin Measurement",
    "blood cohb": "Blood Carboxyhaemoglobin Measurement",
    "Blood cohb": "Blood Carboxyhaemoglobin Measurement",
    "Blood Cohb": "Blood Carboxyhaemoglobin Measurement",
    "Blood COHb": "Blood Carboxyhaemoglobin Measurement",
    "Carboxy-Hb": "Blood Carboxyhaemoglobin Measurement",
    "carboxyhaemoglobin": "Blood Carboxyhaemoglobin Measurement",
    "Carboxyhaemoglobin": "Blood Carboxyhaemoglobin Measurement",
    "blood carboxyhaemoglobin": "Blood Carboxyhaemoglobin Measurement",
    "Blood carboxyhaemoglobin": "Blood Carboxyhaemoglobin Measurement",
    "Blood Carboxyhaemoglobin": "Blood Carboxyhaemoglobin Measurement",
    "Blood Carboxyhaemoglobin Assessment": "Blood Carboxyhaemoglobin Measurement",
    "Blood Carboxyhaemoglobin Measurement": "Blood Carboxyhaemoglobin Measurement",
    "spmet": "Blood Methaemoglobin Measurement",
    "Spmet": "Blood Methaemoglobin Measurement",
    "SpMet": "Blood Methaemoglobin Measurement",
    "SpMET": "Blood Methaemoglobin Measurement",
    "SpMetHb": "Blood Methaemoglobin Measurement",
    "SpMETHb": "Blood Methaemoglobin Measurement",
    "methb": "Blood Methaemoglobin Measurement",
    "Methb": "Blood Methaemoglobin Measurement",
    "MetHb": "Blood Methaemoglobin Measurement",
    "METHb": "Blood Methaemoglobin Measurement",
    "spmet assessment": "Blood Methaemoglobin Measurement",
    "Spmet assessment": "Blood Methaemoglobin Measurement",
    "SpMet assessment": "Blood Methaemoglobin Measurement",
    "SpMetHb assessment": "Blood Methaemoglobin Measurement",
    "SpMet Assessment": "Blood Methaemoglobin Measurement",
    "SpMetHb Assessment": "Blood Methaemoglobin Measurement",
    "spmet measurement": "Blood Methaemoglobin Measurement",
    "Spmet measurement": "Blood Methaemoglobin Measurement",
    "SpMet measurement": "Blood Methaemoglobin Measurement",
    "SpMetHb measurement": "Blood Methaemoglobin Measurement",
    "SpMet Measurement": "Blood Methaemoglobin Measurement",
    "SpMetHb Measurement": "Blood Methaemoglobin Measurement",
    "Met-Hb"    : "Blood Methaemoglobin Measurement",
    "methaemoglobin": "Blood Methaemoglobin Measurement",
    "Methaemoglobin": "Blood Methaemoglobin Measurement",
    "blood methb": "Blood Methaemoglobin Measurement",
    "Blood methb": "Blood Methaemoglobin Measurement",
    "Blood methb": "Blood Methaemoglobin Measurement",
    "Blood MetHb": "Blood Methaemoglobin Measurement",
    "blood methaemoglobin": "Blood Methaemoglobin Measurement",
    "Blood methaemoglobin": "Blood Methaemoglobin Measurement",
    "Blood Methaemoglobin": "Blood Methaemoglobin Measurement",
    "Blood Methaemoglobin Assessment": "Blood Methaemoglobin Measurement",
    "Blood Methaemoglobin Measurement": "Blood Methaemoglobin Measurement",
    "spo2": "Blood Oxygen Saturation Measurement",
    "Spo2": "Blood Oxygen Saturation Measurement",
    "SpO2": "Blood Oxygen Saturation Measurement",
    "spo2 assessment": "Blood Oxygen Saturation Measurement",
    "Spo2 assessment": "Blood Oxygen Saturation Measurement",
    "SpO2 assessment": "Blood Oxygen Saturation Measurement",
    "SpO2 Assessment": "Blood Oxygen Saturation Measurement",
    "spo2 measurement": "Blood Oxygen Saturation Measurement",
    "Spo2 measurement": "Blood Oxygen Saturation Measurement",
    "SpO2 measurement": "Blood Oxygen Saturation Measurement",
    "SpO2 Measurement": "Blood Oxygen Saturation Measurement",
    "sats": "Blood Oxygen Saturation Measurement",
    "Sats": "Blood Oxygen Saturation Measurement",
    "SATS": "Blood Oxygen Saturation Measurement",
    "blood sat": "Blood Oxygen Saturation Measurement",
    "blood sats": "Blood Oxygen Saturation Measurement",
    "Blood sats": "Blood Oxygen Saturation Measurement",
    "Blood Sats": "Blood Oxygen Saturation Measurement",
    "blood oxy sat": "Blood Oxygen Saturation Measurement",
    "Blood oxy sat": "Blood Oxygen Saturation Measurement",
    "Blood Oxy Sat": "Blood Oxygen Saturation Measurement",
    "blood oxygen saturation": "Blood Oxygen Saturation Measurement",
    "Blood oxygen saturation": "Blood Oxygen Saturation Measurement",
    "Blood Oxygen Saturation": "Blood Oxygen Saturation Measurement",
    "blood oxygen saturation levels": "Blood Oxygen Saturation Measurement",
    "Blood oxygen saturation levels": "Blood Oxygen Saturation Measurement",
    "Blood Oxygen Saturation Levels": "Blood Oxygen Saturation Measurement",
    "Blood Oxygen Saturation Assessment": "Blood Oxygen Saturation Measurement",
    "Blood Oxygen Saturation Measurement": "Blood Oxygen Saturation Measurement",
    "burns": "Burn Management",
    "Burns": "Burn Management",
    "burn management": "Burn Management",
    "Burn management": "Burn Management",
    "Burn Management": "Burn Management",
    "burns management": "Burn Management",
    "Burns management": "Burn Management",
    "Burns Management": "Burn Management",
    "bgl": "Capillary Blood Glucose Level Measurement",
    "Bgl": "Capillary Blood Glucose Level Measurement",
    "BGL": "Capillary Blood Glucose Level Measurement",
    "bsl": "Capillary Blood Glucose Level Measurement",
    "Bsl": "Capillary Blood Glucose Level Measurement",
    "BSL": "Capillary Blood Glucose Level Measurement",
    "blood glucose": "Capillary Blood Glucose Level Measurement",
    "Blood glucose": "Capillary Blood Glucose Level Measurement",
    "Blood Glucose": "Capillary Blood Glucose Level Measurement",
    "blood glucose level": "Capillary Blood Glucose Level Measurement",
    "Blood glucose level": "Capillary Blood Glucose Level Measurement",
    "Blood Glucose Level": "Capillary Blood Glucose Level Measurement",
    "blood sugar": "Capillary Blood Glucose Level Measurement",
    "Blood sugar": "Capillary Blood Glucose Level Measurement",
    "Blood Sugar": "Capillary Blood Glucose Level Measurement",
    "blood sugar level": "Capillary Blood Glucose Level Measurement",
    "Blood sugar level": "Capillary Blood Glucose Level Measurement",
    "Blood Sugar Level": "Capillary Blood Glucose Level Measurement",
    "bgl assessment": "Capillary Blood Glucose Level Measurement",
    "Bgl assessment": "Capillary Blood Glucose Level Measurement",
    "BGL assessment": "Capillary Blood Glucose Level Measurement",
    "BGL Assessment": "Capillary Blood Glucose Level Measurement",
    "bsl assessment": "Capillary Blood Glucose Level Measurement",
    "Bsl assessment": "Capillary Blood Glucose Level Measurement",
    "BSL assessment": "Capillary Blood Glucose Level Measurement",
    "BSL Assessment": "Capillary Blood Glucose Level Measurement",
    "bgl measurement": "Capillary Blood Glucose Level Measurement",
    "Bgl measurement": "Capillary Blood Glucose Level Measurement",
    "BGL measurement": "Capillary Blood Glucose Level Measurement",
    "BGL Measurement": "Capillary Blood Glucose Level Measurement",
    "bsl measurement": "Capillary Blood Glucose Level Measurement",
    "Bsl measurement": "Capillary Blood Glucose Level Measurement",
    "BSL measurement": "Capillary Blood Glucose Level Measurement",
    "BSL Measurement": "Capillary Blood Glucose Level Measurement",
    "capillary bgl": "Capillary Blood Glucose Level Measurement",
    "Capillary bgl": "Capillary Blood Glucose Level Measurement",
    "Capillary BGL": "Capillary Blood Glucose Level Measurement",
    "capillary bsl": "Capillary Blood Glucose Level Measurement",
    "Capillary bsl": "Capillary Blood Glucose Level Measurement",
    "Capillary BSL": "Capillary Blood Glucose Level Measurement",
    "glucometry": "Capillary Blood Glucose Level Measurement",
    "Glucometry": "Capillary Blood Glucose Level Measurement",
    "crt": "Capillary Refill Time Assessment",
    "Crt": "Capillary Refill Time Assessment",
    "CRT": "Capillary Refill Time Assessment",
    "dcrt": "Capillary Refill Time Assessment",
    "Dcrt": "Capillary Refill Time Assessment",
    "DCRT": "Capillary Refill Time Assessment",
    "crt assessment": "Capillary Refill Time Assessment",
    "Crt assessment": "Capillary Refill Time Assessment",
    "CRT assessment": "Capillary Refill Time Assessment",
    "CRT Assessment": "Capillary Refill Time Assessment",
    "dcrt assessment": "Capillary Refill Time Assessment",
    "Dcrt assessment": "Capillary Refill Time Assessment",
    "DCRT assessment": "Capillary Refill Time Assessment",
    "DCRT Assessment": "Capillary Refill Time Assessment",
    "crt measurement": "Capillary Refill Time Assessment",
    "Crt measurement": "Capillary Refill Time Assessment",
    "CRT measurement": "Capillary Refill Time Assessment",
    "CRT Measurement": "Capillary Refill Time Assessment",
    "dcrt measurement": "Capillary Refill Time Assessment",
    "Dcrt measurement": "Capillary Refill Time Assessment",
    "DCRT measurement": "Capillary Refill Time Assessment",
    "DCRT Measurement": "Capillary Refill Time Assessment",
    "cap refill": "Capillary Refill Time Assessment",
    "Cap refill": "Capillary Refill Time Assessment",
    "Cap Refill": "Capillary Refill Time Assessment",
    "cap refill time": "Capillary Refill Time Assessment",
    "Cap refill time": "Capillary Refill Time Assessment",
    "Cap Refill Time": "Capillary Refill Time Assessment",
    "digit cap refill": "Capillary Refill Time Assessment",
    "Digit cap refill": "Capillary Refill Time Assessment",
    "Digit Cap Refill": "Capillary Refill Time Assessment",
    "capillary refill time": "Capillary Refill Time Assessment",
    "Capillary refill time": "Capillary Refill Time Assessment",
    "Capillary Refill Time": "Capillary Refill Time Assessment",
    "digit capillary refill time": "Capillary Refill Time Assessment",
    "Digit capillary refill time": "Capillary Refill Time Assessment",
    "Digit Capillary Refill Time": "Capillary Refill Time Assessment",
    "nail blanch": "Capillary Refill Time Assessment",
    "Nail blanch": "Capillary Refill Time Assessment",
    "Nail Blanch": "Capillary Refill Time Assessment",
    "nail blanching test": "Capillary Refill Time Assessment",
    "Nail blanching test": "Capillary Refill Time Assessment",
    "Nail Blanching Test": "Capillary Refill Time Assessment",
    "dbft": "Capillary Refill Time Assessment",
    "Dbft": "Capillary Refill Time Assessment",
    "DBFT": "Capillary Refill Time Assessment",
    "digit blood flow test": "Capillary Refill Time Assessment",
    "Digit blood flow test": "Capillary Refill Time Assessment",
    "Digit Blood Flow Test": "Capillary Refill Time Assessment",
    "digit perfusion test": "Capillary Refill Time Assessment",
    "Digit perfusion test": "Capillary Refill Time Assessment",
    "Digit Perfusion Test": "Capillary Refill Time Assessment",
    "digit perfusion assessment": "Capillary Refill Time Assessment",
    "Digit perfusion assessment": "Capillary Refill Time Assessment",
    "Digit Perfusion Assessment": "Capillary Refill Time Assessment",
    "nail capillary refill test": "Capillary Refill Time Assessment",
    "Nail capillary refill test": "Capillary Refill Time Assessment",
    "Nail Capillary Refill Test": "Capillary Refill Time Assessment",
    "chem burns": "Chemical Burn Management",
    "Chem burns": "Chemical Burn Management",
    "Chem Burns": "Chemical Burn Management",
    "chemical burns": "Chemical Burn Management",
    "Chemical burns": "Chemical Burn Management",
    "Chemical Burns": "Chemical Burn Management",
    "chemical burn management": "Chemical Burn Management",
    "Chemical burn management": "Chemical Burn Management",
    "Chemical Burn Management": "Chemical Burn Management",
    "escharotomy": "Chest Escharotomy",
    "Escharotomy": "Chest Escharotomy",
    "chest escharotomy": "Chest Escharotomy",
    "Chest escharotomy": "Chest Escharotomy",
    "Chest Escharotomy": "Chest Escharotomy",
    "craniectomy": "Emergency Decompressive Craniectomy",
    "Craniectomy": "Emergency Decompressive Craniectomy",
    "decomp crani": "Emergency Decompressive Craniectomy",
    "Decomp crani": "Emergency Decompressive Craniectomy",
    "Decomp Crani": "Emergency Decompressive Craniectomy",
    "decompressive craniectomy": "Emergency Decompressive Craniectomy",
    "Decompressive craniectomy": "Emergency Decompressive Craniectomy",
    "Decompressive Craniectomy": "Emergency Decompressive Craniectomy",
    "emergency dc": "Emergency Decompressive Craniectomy",
    "Emergency dc": "Emergency Decompressive Craniectomy",
    "Emergency DC": "Emergency Decompressive Craniectomy",
    "emergency decompressive craniectomy": "Emergency Decompressive Craniectomy",
    "Emergency decompressive craniectomy": "Emergency Decompressive Craniectomy",
    "Emergency Decompressive Craniectomy": "Emergency Decompressive Craniectomy",
    "limb amputation": "Emergency Extremity Amputation",
    "Limb amputation": "Emergency Extremity Amputation",
    "Limb Amputation": "Emergency Extremity Amputation",
    "extremity amputation": "Emergency Extremity Amputation",
    "Extremity amputation": "Emergency Extremity Amputation",
    "Extremity Amputation": "Emergency Extremity Amputation",
    "emergency amputation": "Emergency Extremity Amputation",
    "Emergency amputation": "Emergency Extremity Amputation",
    "Emergency Amputation": "Emergency Extremity Amputation",
    "emergency limb amputation": "Emergency Extremity Amputation",
    "Emergency limb amputation": "Emergency Extremity Amputation",
    "Emergency Limb Amputation": "Emergency Extremity Amputation",
    "emergency extremity amputation": "Emergency Extremity Amputation",
    "Emergency extremity amputation": "Emergency Extremity Amputation",
    "Emergency Extremity Amputation": "Emergency Extremity Amputation",
    "laparotomy": "Emergency Laparotomy",
    "Laparotomy": "Emergency Laparotomy",
    "emergency laparotomy": "Emergency Laparotomy",
    "Emergency laparotomy": "Emergency Laparotomy",
    "Emergency Laparotomy": "Emergency Laparotomy",
    "ijiv": "Internal Jugular Intravenous Access (Ultrasound-Guided Method)",
    "Ijiv": "Internal Jugular Intravenous Access (Ultrasound-Guided Method)",
    "IJIV": "Internal Jugular Intravenous Access (Ultrasound-Guided Method)",
    "IJIV POCUS guided": "Internal Jugular Intravenous Access (Ultrasound-Guided Method)",
    "IJIV POCUS Guided": "Internal Jugular Intravenous Access (Ultrasound-Guided Method)",
    "IJIV eFAST guided": "Internal Jugular Intravenous Access (Ultrasound-Guided Method)",
    "IJIV eFAST Guided": "Internal Jugular Intravenous Access (Ultrasound-Guided Method)",
    "eFAST Guided IJIV": "Internal Jugular Intravenous Access (Ultrasound-Guided Method)",
    "ultrasound guided ijiv": "Internal Jugular Intravenous Access (Ultrasound-Guided Method)",
    "Ultrasound guided ijiv": "Internal Jugular Intravenous Access (Ultrasound-Guided Method)",
    "Ultrasound Guided IJIV": "Internal Jugular Intravenous Access (Ultrasound-Guided Method)",
    "ultrasound-guided ijiv": "Internal Jugular Intravenous Access (Ultrasound-Guided Method)",
    "Ultrasound-guided ijiv": "Internal Jugular Intravenous Access (Ultrasound-Guided Method)",
    "Ultrasound-Guided IJIV": "Internal Jugular Intravenous Access (Ultrasound-Guided Method)",
    "IM": "Intramuscular Administration",
    "IM inj": "Intramuscular Administration",
    "IM Inj": "Intramuscular Administration",
    "IM INJ": "Intramuscular Administration",
    "intramusc": "Intramuscular Administration",
    "Intramusc": "Intramuscular Administration",
    "intramuscular": "Intramuscular Administration",
    "Intramuscular": "Intramuscular Administration",
    "IM injection": "Intramuscular Administration",
    "IM Injection": "Intramuscular Administration",
    "IM administration": "Intramuscular Administration",
    "IM Administration": "Intramuscular Administration",
    "IO": "Intraosseous Access",
    "IO inj": "Intraosseous Access",
    "IO Inj": "Intraosseous Access",
    "IO INJ": "Intraosseous Access",
    "intraosseous": "Intraosseous Access",
    "Intraosseous": "Intraosseous Access",
    "Intraosseous administration": "Intraosseous Access",
    "Intraosseous Administration": "Intraosseous Access",
    "Intraosseous access": "Intraosseous Access",
    "Intraosseous Access": "Intraosseous Access",
    "icp": "Intraparenchymal Pressure Monitoring",
    "Icp": "Intraparenchymal Pressure Monitoring",
    "ICP": "Intraparenchymal Pressure Monitoring",
    "icp assessment": "Intraparenchymal Pressure Monitoring",
    "Icp assessment": "Intraparenchymal Pressure Monitoring",
    "ICP assessment": "Intraparenchymal Pressure Monitoring",
    "ICP Assessment": "Intraparenchymal Pressure Monitoring",
    "icp measurement": "Intraparenchymal Pressure Monitoring",
    "Icp measurement": "Intraparenchymal Pressure Monitoring",
    "ICP measurement": "Intraparenchymal Pressure Monitoring",
    "ICP Measurement": "Intraparenchymal Pressure Monitoring",
    "icp monitoring": "Intraparenchymal Pressure Monitoring",
    "Icp monitoring": "Intraparenchymal Pressure Monitoring",
    "ICP monitoring": "Intraparenchymal Pressure Monitoring",
    "ICP Monitoring": "Intraparenchymal Pressure Monitoring",
    "ipp monitoring": "Intraparenchymal Pressure Monitoring",
    "Ipp monitoring": "Intraparenchymal Pressure Monitoring",
    "IPP monitoring": "Intraparenchymal Pressure Monitoring",
    "IPP Monitoring": "Intraparenchymal Pressure Monitoring",
    "aneroid bp": "Aneroid Non-Invasive Blood Pressure Measurement",
    "Aneroid bp": "Aneroid Non-Invasive Blood Pressure Measurement",
    "aneroid BP": "Aneroid Non-Invasive Blood Pressure Measurement",
    "Aneroid BP": "Aneroid Non-Invasive Blood Pressure Measurement",
    "aneroid nibp": "Aneroid Non-Invasive Blood Pressure Measurement",
    "Aneroid nibp": "Aneroid Non-Invasive Blood Pressure Measurement",
    "aneroid NIBP": "Aneroid Non-Invasive Blood Pressure Measurement",
    "Aneroid NIBP": "Aneroid Non-Invasive Blood Pressure Measurement",
    "aneroid blood pressure": "Aneroid Non-Invasive Blood Pressure Measurement",
    "Aneroid blood pressure": "Aneroid Non-Invasive Blood Pressure Measurement",
    "Aneroid Blood Pressure": "Aneroid Non-Invasive Blood Pressure Measurement",
    "aneroid nibp measurement": "Aneroid Non-Invasive Blood Pressure Measurement",
    "aneroid NIBP measurement": "Aneroid Non-Invasive Blood Pressure Measurement",
    "Aneroid NIBP measurement": "Aneroid Non-Invasive Blood Pressure Measurement",
    "Aneroid NIBP Measurement": "Aneroid Non-Invasive Blood Pressure Measurement",
    "manual nibp": "Aneroid Non-Invasive Blood Pressure Measurement",
    "Manual nibp": "Aneroid Non-Invasive Blood Pressure Measurement",
    "Manual NIBP": "Aneroid Non-Invasive Blood Pressure Measurement",
    "manual nibp assessment": "Aneroid Non-Invasive Blood Pressure Measurement",
    "Manual nibp assessment": "Aneroid Non-Invasive Blood Pressure Measurement",
    "Manual NIBP Assessment": "Aneroid Non-Invasive Blood Pressure Measurement",
    "manual nibp measurement": "Aneroid Non-Invasive Blood Pressure Measurement",
    "Manual nibp measurement": "Aneroid Non-Invasive Blood Pressure Measurement",
    "Manual NIBP Measurement": "Aneroid Non-Invasive Blood Pressure Measurement",
    "korotkoff nibp": "Aneroid Non-Invasive Blood Pressure Measurement",
    "Korotkoff nibp": "Aneroid Non-Invasive Blood Pressure Measurement",
    "Korotkoff NIBP": "Aneroid Non-Invasive Blood Pressure Measurement",
    "sternotomy": "Midline Sternotomy",
    "Sternotomy": "Midline Sternotomy",
    "midline sternotomy": "Midline Sternotomy",
    "Midline sternotomy": "Midline Sternotomy",
    "Midline Sternotomy": "Midline Sternotomy",
    "needle cric": "Needle Cricothyroidotomy (High-Frequency Jet Ventilation Method)",
    "Needle cric": "Needle Cricothyroidotomy (High-Frequency Jet Ventilation Method)",
    "Needle Cric": "Needle Cricothyroidotomy (High-Frequency Jet Ventilation Method)",
    "needle cricothyrotomy": "Needle Cricothyroidotomy (High-Frequency Jet Ventilation Method)",
    "Needle cricothyrotomy": "Needle Cricothyroidotomy (High-Frequency Jet Ventilation Method)",
    "Needle Cricothyrotomy": "Needle Cricothyroidotomy (High-Frequency Jet Ventilation Method)",
    "needle cricothyroidotomy": "Needle Cricothyroidotomy (High-Frequency Jet Ventilation Method)",
    "Needle cricothyroidotomy": "Needle Cricothyroidotomy (High-Frequency Jet Ventilation Method)",
    "Needle Cricothyroidotomy": "Needle Cricothyroidotomy (High-Frequency Jet Ventilation Method)",
    "hfjv needle cricothyrotomy": "Needle Cricothyroidotomy (High-Frequency Jet Ventilation Method)",
    "Hfjv needle cricothyrotomy": "Needle Cricothyroidotomy (High-Frequency Jet Ventilation Method)",
    "HFJV Needle Cricothyrotomy": "Needle Cricothyroidotomy (High-Frequency Jet Ventilation Method)",
    "hfjv needle cricothyroidotomy": "Needle Cricothyroidotomy (High-Frequency Jet Ventilation Method)",
    "Hfjv needle cricothyroidotomy": "Needle Cricothyroidotomy (High-Frequency Jet Ventilation Method)",
    "HFJV Needle Cricothyroidotomy": "Needle Cricothyroidotomy (High-Frequency Jet Ventilation Method)",
    "hfjv needle cric": "Needle Cricothyroidotomy (High-Frequency Jet Ventilation Method)",
    "Hfjv needle cric": "Needle Cricothyroidotomy (High-Frequency Jet Ventilation Method)",
    "HFJV needle cric": "Needle Cricothyroidotomy (High-Frequency Jet Ventilation Method)",
    "HFJV Needle Cric": "Needle Cricothyroidotomy (High-Frequency Jet Ventilation Method)",
    "needle cric hfjv": "Needle Cricothyroidotomy (High-Frequency Jet Ventilation Method)",
    "Needle cric hfjv": "Needle Cricothyroidotomy (High-Frequency Jet Ventilation Method)",
    "Needle Cric HFJV": "Needle Cricothyroidotomy (High-Frequency Jet Ventilation Method)",
    "needle cric hfjv method": "Needle Cricothyroidotomy (High-Frequency Jet Ventilation Method)",
    "Needle cric hfjv method": "Needle Cricothyroidotomy (High-Frequency Jet Ventilation Method)",
    "Needle Cric HFJV Method": "Needle Cricothyroidotomy (High-Frequency Jet Ventilation Method)",
    "jet vent needle cric": "Needle Cricothyroidotomy (High-Frequency Jet Ventilation Method)",
    "Jet vent needle cric": "Needle Cricothyroidotomy (High-Frequency Jet Ventilation Method)",
    "Jet Vent Needle Cric": "Needle Cricothyroidotomy (High-Frequency Jet Ventilation Method)",
    "jet ventilation needle cric": "Needle Cricothyroidotomy (High-Frequency Jet Ventilation Method)",
    "Jet ventilation needle cric": "Needle Cricothyroidotomy (High-Frequency Jet Ventilation Method)",
    "Jet Ventilation Needle Cric": "Needle Cricothyroidotomy (High-Frequency Jet Ventilation Method)",
    "syringe needle cric": "Needle Cricothyroidotomy (Syringe Method)",
    "Syringe needle cric": "Needle Cricothyroidotomy (Syringe Method)",
    "Syringe Needle Cric": "Needle Cricothyroidotomy (Syringe Method)",
    "syringe method needle cric": "Needle Cricothyroidotomy (Syringe Method)",
    "Syringe method needle cric": "Needle Cricothyroidotomy (Syringe Method)",
    "Syringe Method Needle Cric": "Needle Cricothyroidotomy (Syringe Method)",
    "needle cric syringe method": "Needle Cricothyroidotomy (Syringe Method)",
    "Needle cric syringe method": "Needle Cricothyroidotomy (Syringe Method)",
    "Needle Cric Syringe Method": "Needle Cricothyroidotomy (Syringe Method)",
    "needle thoracostomy": "Needle Thoracostomy",
    "Needle thoracostomy": "Needle Thoracostomy",
    "Needle Thoracostomy": "Needle Thoracostomy",
    "ndp": "Needle Thoracostomy",
    "Ndp": "Needle Thoracostomy",
    "needle decompression": "Needle Thoracostomy",
    "Needle decompression": "Needle Thoracostomy",
    "Needle Decompression": "Needle Thoracostomy",
    "chest decompression": "Needle Thoracostomy",
    "Chest decompression": "Needle Thoracostomy",
    "Chest Decompression": "Needle Thoracostomy",
    "penthrox": "Penthrox Whistle",
    "Penthrox": "Penthrox Whistle",
    "green whistle": "Penthrox Whistle",
    "Green whistle": "Penthrox Whistle",
    "Green Whistle": "Penthrox Whistle",
    "penthrox whistle": "Penthrox Whistle",
    "Penthrox whistle": "Penthrox Whistle",
    "Penthrox Whistle": "Penthrox Whistle",
    "pericard": "Pericardiocentesis (Syringe Method)",
    "Pericard": "Pericardiocentesis (Syringe Method)",
    "pericard.": "Pericardiocentesis (Syringe Method)",
    "Pericard.": "Pericardiocentesis (Syringe Method)",
    "pericardiocentesis": "Pericardiocentesis (Syringe Method)",
    "Pericardiocentesis": "Pericardiocentesis (Syringe Method)",
    "syringe pericardiocentesis": "Pericardiocentesis (Syringe Method)",
    "Syringe pericardiocentesis": "Pericardiocentesis (Syringe Method)",
    "Syringe Pericardiocentesis": "Pericardiocentesis (Syringe Method)",
    "syringe method pericardiocentesis": "Pericardiocentesis (Syringe Method)",
    "Syringe method pericardiocentesis": "Pericardiocentesis (Syringe Method)",
    "Syringe Method Pericardiocentesis": "Pericardiocentesis (Syringe Method)",
    "piv": "Peripheral Intravenous Access",
    "pIV": "Peripheral Intravenous Access",
    "iv": "Peripheral Intravenous Access",
    "IV": "Peripheral Intravenous Access",
    "IV inj": "Peripheral Intravenous Access",
    "IV Inj": "Peripheral Intravenous Access",
    "IV INJ": "Peripheral Intravenous Access",
    "iv access": "Peripheral Intravenous Access",
    "IV access": "Peripheral Intravenous Access",
    "IV Access": "Peripheral Intravenous Access",
    "piv access": "Peripheral Intravenous Access",
    "pIV access": "Peripheral Intravenous Access",
    "pIV Access": "Peripheral Intravenous Access",
    "iv line": "Peripheral Intravenous Access",
    "IV line": "Peripheral Intravenous Access",
    "IV Line": "Peripheral Intravenous Access",
    "piv line": "Peripheral Intravenous Access",
    "pIV line": "Peripheral Intravenous Access",
    "pIV Line": "Peripheral Intravenous Access",
    "intravenous": "Peripheral Intravenous Access",
    "Intravenous": "Peripheral Intravenous Access",
    "intravenous access": "Peripheral Intravenous Access",
    "Intravenous access": "Peripheral Intravenous Access",
    "Intravenous Access": "Peripheral Intravenous Access",
    "intravenous line": "Peripheral Intravenous Access",
    "Intravenous line": "Peripheral Intravenous Access",
    "Intravenous Line": "Peripheral Intravenous Access",
    "intravenous line placement": "Peripheral Intravenous Access",
    "Intravenous line placement": "Peripheral Intravenous Access",
    "Intravenous Line Placement": "Peripheral Intravenous Access",
    "peripheral iv": "Peripheral Intravenous Access",
    "peripheral IV": "Peripheral Intravenous Access",
    "Peripheral IV": "Peripheral Intravenous Access",
    "peripheral intravenous line placement": "Peripheral Intravenous Access",
    "Peripheral intravenous line placement": "Peripheral Intravenous Access",
    "Peripheral Intravenous Line Placement": "Peripheral Intravenous Access",
    "peripheral intravenous access": "Peripheral Intravenous Access",
    "Peripheral intravenous access": "Peripheral Intravenous Access",
    "Peripheral Intravenous Access": "Peripheral Intravenous Access",
    "rsi": "Rapid Sequence Intubation",
    "Rsi": "Rapid Sequence Intubation",
    "RSI": "Rapid Sequence Intubation",
    "cico": "Rapid Sequence Intubation",
    "CICO": "Rapid Sequence Intubation",
    "cicv": "Rapid Sequence Intubation",
    "CICV": "Rapid Sequence Intubation",
    "CI, CO": "Rapid Sequence Intubation",
    "CI, CV": "Rapid Sequence Intubation",
    "rapid sequence induction": "Rapid Sequence Intubation",
    "Rapid sequence induction": "Rapid Sequence Intubation",
    "Rapid Sequence Induction": "Rapid Sequence Intubation",
    "rapid sequence intubation": "Rapid Sequence Intubation",
    "Rapid sequence intubation": "Rapid Sequence Intubation",
    "Rapid Sequence Intubation": "Rapid Sequence Intubation",
    "sc": "Subcutaneous Administration",
    "Sc": "Subcutaneous Administration",
    "SC": "Subcutaneous Administration",
    "sc inj": "Subcutaneous Administration",
    "SC inj": "Subcutaneous Administration",
    "SC Inj": "Subcutaneous Administration",
    "SC INJ": "Subcutaneous Administration",
    "subcutan.": "Subcutaneous Administration",
    "Subcutan.": "Subcutaneous Administration",
    "sc injection": "Subcutaneous Administration",
    "SC injection": "Subcutaneous Administration",
    "SC Injection": "Subcutaneous Administration",
    "subcutaneous injection": "Subcutaneous Administration",
    "Subcutaneous injection": "Subcutaneous Administration",
    "Subcutaneous Injection": "Subcutaneous Administration",
    "subcutaneous administration": "Subcutaneous Administration",
    "Subcutaneous administration": "Subcutaneous Administration",
    "Subcutaneous Administration": "Subcutaneous Administration",
    "surgi cric": "Surgical Cricothyroidotomy",
    "Surgi cric": "Surgical Cricothyroidotomy",
    "Surgi Cric": "Surgical Cricothyroidotomy",
    "surgical cricothyrotomy": "Surgical Cricothyroidotomy",
    "Surgical cricothyrotomy": "Surgical Cricothyroidotomy",
    "Surgical Cricothyrotomy": "Surgical Cricothyroidotomy",
    "surgical cricothyroidotomy": "Surgical Cricothyroidotomy",
    "Surgical cricothyroidotomy": "Surgical Cricothyroidotomy",
    "Surgical Cricothyroidotomy": "Surgical Cricothyroidotomy",
    "stt": "Surgical Tube Thoracostomy",
    "Stt": "Surgical Tube Thoracostomy",
    "STT": "Surgical Tube Thoracostomy",
    "tube thoracostomy": "Surgical Tube Thoracostomy",
    "Tube thoracostomy": "Surgical Tube Thoracostomy",
    "Tube Thoracostomy": "Surgical Tube Thoracostomy",
    "surgical tube thoracostomy": "Surgical Tube Thoracostomy",
    "Surgical tube thoracostomy": "Surgical Tube Thoracostomy",
    "Surgical Tube Thoracostomy": "Surgical Tube Thoracostomy",
    "tcp": "Transcutaneous Pacing",
    "Tcp": "Transcutaneous Pacing",
    "TcP": "Transcutaneous Pacing",
    "TCP": "Transcutaneous Pacing",
    "pacing": "Transcutaneous Pacing",
    "Pacing": "Transcutaneous Pacing",
    "cardiac pacing": "Transcutaneous Pacing",
    "Cardiac pacing": "Transcutaneous Pacing",
    "Cardiac Pacing": "Transcutaneous Pacing",
    "trancutaneous pacing": "Transcutaneous Pacing",
    "Transcutaneous pacing": "Transcutaneous Pacing",
    "Transcutaneous Pacing": "Transcutaneous Pacing",
    "ysd": "Yankauer Suction Device",
    "Ysd": "Yankauer Suction Device",
    "YSD": "Yankauer Suction Device",
    "yankauer": "Yankauer Suction Device",
    "Yankauer": "Yankauer Suction Device",
    "yankauer suction": "Yankauer Suction Device",
    "Yankauer suction": "Yankauer Suction Device",
    "Yankauer Suction": "Yankauer Suction Device",
    "yankauer suction device": "Yankauer Suction Device",
    "Yankauer suction device": "Yankauer Suction Device",
    "Yankauer Suction Device": "Yankauer Suction Device",
    "yankauer suction catheter": "Yankauer Suction Device",
    "Yankauer suction catheter": "Yankauer Suction Device",
    "Yankauer Suction Catheter": "Yankauer Suction Device",
    "ejiv": "External Jugular Intravenous Access (Landmark Method)",
    "Ejiv": "External Jugular Intravenous Access (Landmark Method)",
    "EJIV": "External Jugular Intravenous Access (Landmark Method)",
    "landmark ejiv": "External Jugular Intravenous Access (Landmark Method)",
    "Landmark ejiv": "External Jugular Intravenous Access (Landmark Method)",
    "Landmark EJIV": "External Jugular Intravenous Access (Landmark Method)",
    "ejiv landmark method": "External Jugular Intravenous Access (Landmark Method)",
    "EJIV landmark method": "External Jugular Intravenous Access (Landmark Method)",
    "EJIV Landmark Method": "External Jugular Intravenous Access (Landmark Method)",
    "ett": "Endotracheal Tube Intubation",
    "Ett": "Endotracheal Tube Intubation",
    "ETT": "Endotracheal Tube Intubation",
    "etti": "Endotracheal Tube Intubation",
    "Etti": "Endotracheal Tube Intubation",
    "ETTI": "Endotracheal Tube Intubation",
    "ETI": "Endotracheal Tube Intubation",
    "et tube": "Endotracheal Tube Intubation",
    "ET tube": "Endotracheal Tube Intubation",
    "ET Tube": "Endotracheal Tube Intubation",
    "et insertion": "Endotracheal Tube Intubation",
    "ET insertion": "Endotracheal Tube Intubation",
    "ET Insertion": "Endotracheal Tube Intubation",
    "et intubation": "Endotracheal Tube Intubation",
    "ET intubation": "Endotracheal Tube Intubation",
    "ET Intubation": "Endotracheal Tube Intubation",
    "ett insertion": "Endotracheal Tube Intubation",
    "ETT insertion": "Endotracheal Tube Intubation",
    "ETT Insertion": "Endotracheal Tube Intubation",
    "ett intubation": "Endotracheal Tube Intubation",
    "ETT intubation": "Endotracheal Tube Intubation",
    "ETT Intubation": "Endotracheal Tube Intubation",
    "et tube insertion": "Endotracheal Tube Intubation",
    "ET tube insertion": "Endotracheal Tube Intubation",
    "ET Tube Insertion": "Endotracheal Tube Intubation",
    "et tube intubation": "Endotracheal Tube Intubation",
    "ET tube intubation": "Endotracheal Tube Intubation",
    "ET Tube Intubation": "Endotracheal Tube Intubation",
    "endotracheal intubation": "Endotracheal Tube Intubation",
    "Endotracheal intubation": "Endotracheal Tube Intubation",
    "Endotracheal Intubation": "Endotracheal Tube Intubation",
    "endotracheal tube insertion": "Endotracheal Tube Intubation",
    "Endotracheal tube insertion": "Endotracheal Tube Intubation",
    "Endotracheal Tube Insertion": "Endotracheal Tube Intubation",
    "endotracheal tube intubation": "Endotracheal Tube Intubation",
    "Endotracheal tube intubation": "Endotracheal Tube Intubation",
    "Endotracheal Tube Intubation": "Endotracheal Tube Intubation",
    "chem burn": "Chemical Burn Management",
    "Chem burn": "Chemical Burn Management",
    "Chem Burn": "Chemical Burn Management",
    "chem burns": "Chemical Burn Management",
    "Chem burns": "Chemical Burn Management",
    "Chem Burns": "Chemical Burn Management",
    "chemical burn": "Chemical Burn Management",
    "Chemical burn": "Chemical Burn Management",
    "Chemical Burn": "Chemical Burn Management",
    "chemical burns": "Chemical Burn Management",
    "Chemical burns": "Chemical Burn Management",
    "Chemical Burns": "Chemical Burn Management",
    "chem burn mgmt": "Chemical Burn Management",
    "Chem burn mgmt": "Chemical Burn Management",
    "Chem Burn Mgmt": "Chemical Burn Management",
    "chem burn mgmt.": "Chemical Burn Management",
    "Chem burn mgmt.": "Chemical Burn Management",
    "Chem Burn Mgmt.": "Chemical Burn Management",
    "chemical burn management": "Chemical Burn Management",
    "Chemical burn management": "Chemical Burn Management",
    "Chemical Burn Management": "Chemical Burn Management",
    "impalement": "Emergency Removal of Embedded Objects",
    "Impalement": "Emergency Removal of Embedded Objects",
    "patient impaled": "Emergency Removal of Embedded Objects",
    "Patient impaled": "Emergency Removal of Embedded Objects",
    "Patient Impaled": "Emergency Removal of Embedded Objects",
    "impaled pt": "Emergency Removal of Embedded Objects",
    "Impaled pt": "Emergency Removal of Embedded Objects",
    "impaled PT": "Emergency Removal of Embedded Objects",
    "Impaled PT": "Emergency Removal of Embedded Objects",
    "impaled patient": "Emergency Removal of Embedded Objects",
    "Impaled patient": "Emergency Removal of Embedded Objects",
    "Impaled Patient": "Emergency Removal of Embedded Objects",
    "patient impalement": "Emergency Removal of Embedded Objects",
    "Patient impalement": "Emergency Removal of Embedded Objects",
    "Patient Impalement": "Emergency Removal of Embedded Objects",
    "impaling object": "Emergency Removal of Embedded Objects",
    "Impaling object": "Emergency Removal of Embedded Objects",
    "Impaling Object": "Emergency Removal of Embedded Objects",
    "impaling objects": "Emergency Removal of Embedded Objects",
    "Impaling objects": "Emergency Removal of Embedded Objects",
    "Impaling Objects": "Emergency Removal of Embedded Objects",
    "embedded object": "Emergency Removal of Embedded Objects",
    "Embedded object": "Emergency Removal of Embedded Objects",
    "Embedded Object": "Emergency Removal of Embedded Objects",
    "impaling object removal": "Emergency Removal of Embedded Objects",
    "Impaling object removal": "Emergency Removal of Embedded Objects",
    "Impaling Object Removal": "Emergency Removal of Embedded Objects",
    "embedded object removal": "Emergency Removal of Embedded Objects",
    "Embedded object removal": "Emergency Removal of Embedded Objects",
    "Embedded Object Removal": "Emergency Removal of Embedded Objects",
    "emergency removal of impaling objects": "Emergency Removal of Embedded Objects",
    "Emergency removal of impaling objects": "Emergency Removal of Embedded Objects",
    "Emergency Removal of Impaling Objects": "Emergency Removal of Embedded Objects",
    "Emergency Removal Of Impaling Objects": "Emergency Removal of Embedded Objects",
    "emergency removal of embedded objects": "Emergency Removal of Embedded Objects",
    "Emergency removal of embedded objects": "Emergency Removal of Embedded Objects",
    "Emergency Removal of Embedded Objects": "Emergency Removal of Embedded Objects",
    "Emergency Removal Of Embedded Objects": "Emergency Removal of Embedded Objects",
    "vvecmo": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Vvecmo": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "VVECMO": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "vv ecmo": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Vv ecmo": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Vv Ecmo": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "VV ECMO": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "vv-ecmo": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Vv-ecmo": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "VV-ECMO": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "vv-ecmo (dlc)": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Vv-ecmo (dlc)": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "VV-ECMO (DLC)": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "2lc vv-ecmo": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "2LC vv-ecmo": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "2LC Vv-ecmo": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "2LC VV-ECMO": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "dlc vv-ecmo": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Dlc vv-ecmo": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Dlc Vv-ecmo": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "DLC VV-ECMO": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "dual lumen vv-ecmo": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "dual lumen VV-ECMO": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Dual lumen vv-ecmo": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Dual lumen VV-ECMO": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Dual Lumen Vv-ecmo": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Dual Lumen VV-ECMO": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "dual lumen vv ecmo": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "dual lumen VV ECMO": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Dual lumen vv ecmo": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Dual lumen VV ECMO": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Dual Lumen Vv Ecmo": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Dual Lumen VV ECMO": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "two lumen cannula vv ecmo": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Two lumen cannula vv ecmo": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Two Lumen Cannula Vv Ecmo": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "two lumen cannula vv-ecmo": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Two lumen cannula vv-ecmo": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Two Lumen Cannula Vv-ecmo": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "two lumen cannula VV-ECMO": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Two lumen cannula VV-ECMO": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Two Lumen Cannula VV-ECMO": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "dual-lumen cannula vv ecmo": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Dual-lumen cannula vv ecmo": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Dual-Lumen Cannula Vv Ecmo": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "dual-lumen cannula vv-ecmo": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Dual-lumen cannula vv-ecmo": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Dual-Lumen Cannula Vv-ecmo": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "dual-lumen cannula VV-ECMO": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Dual-lumen cannula VV-ECMO": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Dual-Lumen Cannula VV-ECMO": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "dual lumen cannula vv ecmo": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Dual lumen cannula vv ecmo": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Dual Lumen Cannula Vv Ecmo": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "dual lumen cannula vv-ecmo": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Dual lumen cannula vv-ecmo": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Dual Lumen Cannula Vv-ecmo": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "dual lumen cannula VV-ECMO": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Dual lumen cannula VV-ECMO": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Dual Lumen Cannula VV-ECMO": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "veno-venous ecmo": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Veno-venous ecmo": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Veno venous ECMO": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Veno Venous ECMO": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "veno-venous ecmo": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Veno-venous ecmo": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Veno-venous ECMO": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Veno-Venous ECMO": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "2lc veno venous ecmo": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "2lc veno venous ECMO": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "2Lc veno venous ecmo": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "2LC veno venous ecmo": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "2LC Veno venous ecmo": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "2LC Veno venous ECMO": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "2LC Veno Venous Ecmo": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "2LC Veno Venous ECMO": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "2lc veno-venous ecmo": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "2lc veno-venous ECMO": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "2Lc veno-venous ecmo": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "2LC veno-venous ecmo": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "2LC Veno-venous ecmo": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "2LC Veno-venous ECMO": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "2LC Veno-Venous Ecmo": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "2LC Veno-Venous ECMO": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "vv extracorporeal membrane oxygenation": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Vv extracorporeal membrane oxygenation": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "VV extracorporeal membrane oxygenation": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "VV Extracorporeal Membrane Oxygenation": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "veno venous extracorporeal membrane oxygenation": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Veno venous extracorporeal membrane oxygenation": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Veno Venous Extracorporeal Membrane Oxygenation": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "veno-venous extracorporeal membrane oxygenation": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Veno-venous extracorporeal membrane oxygenation": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Veno-venous Extracorporeal Membrane Oxygenation": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Veno-Venous Extracorporeal Membrane Oxygenation": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "dual lumen cannula veno-venous extracorporeal membrane oxygenation": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Dual lumen cannula veno-venous extracorporeal membrane oxygenation": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Dual Lumen Cannula Veno-Venous Extracorporeal Membrane Oxygenation": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "dual-lumen cannula veno-venous extracorporeal membrane oxygenation": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Dual-lumen cannula veno-venous extracorporeal membrane oxygenation": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Dual-Lumen Cannula Veno-Venous Extracorporeal Membrane Oxygenation": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "veno-venous extracorporeal membrane oxygenation (dual lumen cannulae)": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Veno-venous extracorporeal membrane oxygenation (dual lumen cannulae)": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Veno-venous Extracorporeal Membrane Oxygenation (Dual Lumen Cannulae)": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Veno-Venous Extracorporeal Membrane Oxygenation (Dual Lumen Cannulae)": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "veno-venous extracorporeal membrane oxygenation (dual-lumen cannulae)": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Veno-venous extracorporeal membrane oxygenation (dual-lumen cannulae)": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Veno-venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)": "Veno-Venous Extracorporeal Membrane Oxygenation (Dual-Lumen Cannulae)",
    "sbt": "Whole Blood Transfusion",
    "Sbt": "Whole Blood Transfusion",
    "SBT": "Whole Blood Transfusion",
    "bt": "Whole Blood Transfusion",
    "Bt": "Whole Blood Transfusion",
    "BT": "Whole Blood Transfusion",
    "btt": "Whole Blood Transfusion",
    "Btt": "Whole Blood Transfusion",
    "BTT": "Whole Blood Transfusion",
    "blood trans": "Whole Blood Transfusion",
    "Blood trans": "Whole Blood Transfusion",
    "Blood Trans": "Whole Blood Transfusion",
    "blood transfusion": "Whole Blood Transfusion",
    "Blood transfusion": "Whole Blood Transfusion",
    "Blood Transfusion": "Whole Blood Transfusion",
    "emergency transfusion": "Whole Blood Transfusion",
    "Emergency transfusion": "Whole Blood Transfusion",
    "Emergency Transfusion": "Whole Blood Transfusion",
    "simple blood transfusion": "Whole Blood Transfusion",
    "Simple blood transfusion": "Whole Blood Transfusion",
    "Simple Blood Transfusion": "Whole Blood Transfusion",
    "emergency blood transfusion": "Whole Blood Transfusion",
    "Emergency blood transfusion": "Whole Blood Transfusion",
    "Emergency Blood Transfusion": "Whole Blood Transfusion",
    "b trans": "Whole Blood Transfusion",
    "B trans": "Whole Blood Transfusion",
    "B Trans": "Whole Blood Transfusion",
    "transfusion": "Whole Blood Transfusion",
    "Transfusion": "Whole Blood Transfusion",
    "wbt": "Whole Blood Transfusion",
    "Wbt": "Whole Blood Transfusion",
    "WBT": "Whole Blood Transfusion",
    "whole blood transfusion": "Whole Blood Transfusion",
    "Whole blood transfusion": "Whole Blood Transfusion",
    "Whole Blood Transfusion": "Whole Blood Transfusion",
    "lma": "Laryngeal Mask Airway",
    "Lma": "Laryngeal Mask Airway",
    "LMA": "Laryngeal Mask Airway",
    "laryngeal airway": "Laryngeal Mask Airway",
    "Laryngeal airway": "Laryngeal Mask Airway",
    "Laryngeal Airway": "Laryngeal Mask Airway",
    "laryngeal mask": "Laryngeal Mask Airway",
    "Laryngeal mask": "Laryngeal Mask Airway",
    "Laryngeal Mask": "Laryngeal Mask Airway",
    "laryngeal mask airway": "Laryngeal Mask Airway",
    "Laryngeal mask airway": "Laryngeal Mask Airway",
    "Laryngeal Mask Airway": "Laryngeal Mask Airway",
    "opa": "Oropharyngeal Airway",
    "Opa": "Oropharyngeal Airway",
    "OPA": "Oropharyngeal Airway",
    "op tube": "Oropharyngeal Airway",
    "Op tube": "Oropharyngeal Airway",
    "Op Tube": "Oropharyngeal Airway",
    "OP tube": "Oropharyngeal Airway",
    "OP Tube": "Oropharyngeal Airway",
    "oro airway": "Oropharyngeal Airway",
    "Oro airway": "Oropharyngeal Airway",
    "Oro Airway": "Oropharyngeal Airway",
    "oropharyngeal airway": "Oropharyngeal Airway",
    "Oropharyngeal airway": "Oropharyngeal Airway",
    "Oropharyngeal Airway": "Oropharyngeal Airway",
    "oropharyngeal tube": "Oropharyngeal Airway",
    "Oropharyngeal tube": "Oropharyngeal Airway",
    "Oropharyngeal Tube": "Oropharyngeal Airway",
}